title: David Jackson
#description: TBC
logo: assets/profile_DJ.JPG
theme: jekyll-theme-minimal
social_links:
  linkedin: https://www.linkedin.com/in/david-jackson-2a79a722a/
  github: https://github.com/davidjackson99
