title: David Jackson
description: Find me on <a href='https://www.linkedin.com/in/david-jackson-2a79a722a/'>LinkedIn</a> or <a href='https://github.com/davidjackson99'>GitHub</a>!
logo: assets/profile_DJ.JPG
theme: jekyll-theme-minimal
